<!DOCTYPE html>
<html lang="en">
<head>
  
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="author" content="内部使用">
    <link rel="canonical" href="https://secnn.com/%E5%BC%80%E5%8F%91%E6%A1%86%E6%9E%B6%E6%BC%8F%E6%B4%9E/Django%20debug%20page%20XSS%E6%BC%8F%E6%B4%9E%20CVE-2017-12794/">
    <link rel="shortcut icon" href="../../favicon.ico">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title>Django debug page XSS 漏洞 CVE-2017-12794 - SecNN-Wiki漏洞库管理系统&网络安全知识库-本Wiki所有信息来源于公开漏洞数据库</title>
    <link href="../../css/bootstrap-3.3.7.min.css" rel="stylesheet">
    <link href="../../css/font-awesome-4.7.0.css" rel="stylesheet">
    <link href="../../css/base.css" rel="stylesheet">
    <link rel="stylesheet" href="../../css/highlight.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="../../js/jquery-3.2.1.min.js"></script>
    <script src="../../js/bootstrap-3.3.7.min.js"></script>
    <script src="../../js/highlight.pack.js"></script>
    
    <base target="_top">
    <script>
      var base_url = '../..';
      var is_top_frame = false;
        
        var pageToc = [
          {title: "Django debug page XSS \u6f0f\u6d1e CVE-2017-12794", url: "#_top", children: [
              {title: "\u6f0f\u6d1e\u63cf\u8ff0", url: "#_1" },
              {title: "\u8865\u4e01\u5206\u6790", url: "#_2" },
              {title: "\u529f\u80fd\u70b9\u5206\u6790", url: "#_3" },
              {title: "\u73af\u5883\u642d\u5efa", url: "#_4" },
              {title: "\u6f0f\u6d1e\u590d\u73b0", url: "#_5" },
          ]},
        ];

    </script>
    <script src="../../js/base.js"></script>
      <script src="../../search/main.js"></script> 
</head>

<body>
<script>
if (is_top_frame) { $('body').addClass('wm-top-page'); }
</script>



<div class="container-fluid wm-page-content">
  <a name="_top"></a>
    

    
    
      
    

  <div class="row wm-article-nav-buttons" role="navigation" aria-label="navigation">
    
    <div class="wm-article-nav pull-right">
      <a href="../FastAdmin%20%E8%BF%9C%E7%A8%8B%E4%BB%A3%E7%A0%81%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E/" class="btn btn-xs btn-default pull-right">
        Next
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
      </a>
      <a href="../FastAdmin%20%E8%BF%9C%E7%A8%8B%E4%BB%A3%E7%A0%81%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E/" class="btn btn-xs btn-link">
        FastAdmin 远程代码执行漏洞
      </a>
    </div>
    
    <div class="wm-article-nav">
      <a href="../Django%20Trunc%28kind%29%20and%20Extract%28lookup_name%29%20SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E%20CVE-2022-34265/" class="btn btn-xs btn-default pull-left">
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
        Previous</a><a href="../Django%20Trunc%28kind%29%20and%20Extract%28lookup_name%29%20SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E%20CVE-2022-34265/" class="btn btn-xs btn-link">
        Django Trunc(kind) and Extract(lookup_name) SQL 注入漏洞 CVE-2022-34265
      </a>
    </div>
    
  </div>

    

    <h1 id="django-debug-page-xss-cve-2017-12794">Django debug page XSS 漏洞 CVE-2017-12794<a class="headerlink" href="#django-debug-page-xss-cve-2017-12794" title="Permanent link">&para;</a></h1>
<h2 id="_1">漏洞描述<a class="headerlink" href="#_1" title="Permanent link">&para;</a></h2>
<p>Django 发布了新版本 1.11.5，修复了 500 页面中可能存在的一个 XSS 漏洞，这篇文章说明一下该漏洞的原理和复现。</p>
<h2 id="_2">补丁分析<a class="headerlink" href="#_2" title="Permanent link">&para;</a></h2>
<p>因为官方说明是 500 页面中出现的 BUG，所以我们重点关注的就是 <code>django/views/debug.py</code>。</p>
<p>Github 上有 Django 的仓库，下载下来，用 1.11.4 和 1.11.5 进行比较：</p>
<div class="highlight"><pre><span></span><code>git<span class="w"> </span>clone<span class="w"> </span>https://github.com/django/django.git
<span class="nb">cd</span><span class="w"> </span>django
git<span class="w"> </span>diff<span class="w"> </span><span class="m">1</span>.11.4<span class="w"> </span><span class="m">1</span>.11.5<span class="w"> </span>django/views/debug.py
</code></pre></div>
<p><img alt="image-20220222143150033" src="../images/202202221431270.png" /></p>
<div class="highlight"><pre><span></span><code>The above exception ({{ frame.exc_cause }}) was the direct cause of the following exception:
-------------------------------------
The above exception ({{ frame.exc_cause|force_escape }}) was the direct cause of the following exception:
</code></pre></div>
<p>可见，外部关闭了全局转义，然后在这两个地方增加了强制转义。那么，漏洞肯定是在这个位置触发的。</p>
<h2 id="_3">功能点分析<a class="headerlink" href="#_3" title="Permanent link">&para;</a></h2>
<p>如果要触发这两个输出点，就必须进入这个 if 语句：<code>{% ifchanged frame.exc_cause %}{% if frame.exc_cause %}</code>。</p>
<p>可以做个简单的测试，在 Django 命令行下，我们创建一个 username 为 phith0n 的用户，然后再次创建一个 username 为 phith0n 的用户，则会抛出一个 <code>IntegrityError</code> 异常。</p>
<p><img alt="sp170908_040738" src="../images/sp170908_040738.png" /></p>
<p>见上图，原因是触发了数据库的 Unique 异常。</p>
<p>为什么 Django 会引入这样一个异常机制？这是为了方便开发者进行 SQL 错误的调试，因为 Django 的模型最终是操作数据库，数据库中具体出现什么错误，是 Django 无法 100% 预测的。那么，为了方便开发者快速找到是哪个操作触发了数据库异常，就需要将这两个异常回溯栈关联到一块。</p>
<p>我们可以看看代码，<code>django/db/utils.py</code> 的 <code>__exit__</code> 函数：</p>
<div class="highlight"><pre><span></span><code><span class="k">def</span><span class="w"> </span><span class="fm">__exit__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">exc_type</span><span class="p">,</span> <span class="n">exc_value</span><span class="p">,</span> <span class="n">traceback</span><span class="p">):</span>
    <span class="k">if</span> <span class="n">exc_type</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span>
        <span class="k">return</span>
    <span class="k">for</span> <span class="n">dj_exc_type</span> <span class="ow">in</span> <span class="p">(</span>
            <span class="n">DataError</span><span class="p">,</span>
            <span class="n">OperationalError</span><span class="p">,</span>
            <span class="n">IntegrityError</span><span class="p">,</span>
            <span class="n">InternalError</span><span class="p">,</span>
            <span class="n">ProgrammingError</span><span class="p">,</span>
            <span class="n">NotSupportedError</span><span class="p">,</span>
            <span class="n">DatabaseError</span><span class="p">,</span>
            <span class="n">InterfaceError</span><span class="p">,</span>
            <span class="n">Error</span><span class="p">,</span>
    <span class="p">):</span>
        <span class="n">db_exc_type</span> <span class="o">=</span> <span class="nb">getattr</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">wrapper</span><span class="o">.</span><span class="n">Database</span><span class="p">,</span> <span class="n">dj_exc_type</span><span class="o">.</span><span class="vm">__name__</span><span class="p">)</span>
        <span class="k">if</span> <span class="nb">issubclass</span><span class="p">(</span><span class="n">exc_type</span><span class="p">,</span> <span class="n">db_exc_type</span><span class="p">):</span>
            <span class="n">dj_exc_value</span> <span class="o">=</span> <span class="n">dj_exc_type</span><span class="p">(</span><span class="o">*</span><span class="n">exc_value</span><span class="o">.</span><span class="n">args</span><span class="p">)</span>
            <span class="n">dj_exc_value</span><span class="o">.</span><span class="n">__cause__</span> <span class="o">=</span> <span class="n">exc_value</span>
            <span class="k">if</span> <span class="ow">not</span> <span class="nb">hasattr</span><span class="p">(</span><span class="n">exc_value</span><span class="p">,</span> <span class="s1">&#39;__traceback__&#39;</span><span class="p">):</span>
                <span class="n">exc_value</span><span class="o">.</span><span class="n">__traceback__</span> <span class="o">=</span> <span class="n">traceback</span>
            <span class="c1"># Only set the &#39;errors_occurred&#39; flag for errors that may make</span>
            <span class="c1"># the connection unusable.</span>
            <span class="k">if</span> <span class="n">dj_exc_type</span> <span class="ow">not</span> <span class="ow">in</span> <span class="p">(</span><span class="n">DataError</span><span class="p">,</span> <span class="n">IntegrityError</span><span class="p">):</span>
                <span class="bp">self</span><span class="o">.</span><span class="n">wrapper</span><span class="o">.</span><span class="n">errors_occurred</span> <span class="o">=</span> <span class="kc">True</span>
            <span class="n">six</span><span class="o">.</span><span class="n">reraise</span><span class="p">(</span><span class="n">dj_exc_type</span><span class="p">,</span> <span class="n">dj_exc_value</span><span class="p">,</span> <span class="n">traceback</span><span class="p">)</span>
</code></pre></div>
<p>其中 <code>exc_type</code> 是异常，如果其类型是 <code>DataError,OperationalError,IntegrityError,InternalError,ProgrammingError,NotSupportedError,DatabaseError,InterfaceError,Error</code> 之一，则抛出一个同类型的新异常，并设置其 <code>__cause__</code> 和 <code>__traceback__</code> 为此时上下文的 <code>exc_value</code> 和 <code>traceback</code>。</p>
<p><code>exc_value</code> 是上一个异常的说明，<code>traceback</code> 是上一个异常的回溯栈。这个函数其实就是关联了上一个异常和当前的新异常。</p>
<p>最后，在 500 页面中，<code>__cause__</code> 被输出。</p>
<h2 id="_4">环境搭建<a class="headerlink" href="#_4" title="Permanent link">&para;</a></h2>
<p>Vulhub 编译及启动环境：</p>
<div class="highlight"><pre><span></span><code>/docker-compose up -d
</code></pre></div>
<h2 id="_5">漏洞复现<a class="headerlink" href="#_5" title="Permanent link">&para;</a></h2>
<p>在使用 Postgres 数据库并触发异常的时候，psycopg2 会将字段名和字段值全部抛出。那么，如果字段值中包含我们可控的字符串，这个字符串其实就会被设置成 <code>__cause__</code>，最后被显示在页面中。</p>
<p>所以我们假设有如下场景：</p>
<ol>
<li>用户注册页面，未检查用户名</li>
<li>注册一个用户名为 <code>&lt;script&gt;alert(1)&lt;/script&gt;</code> 的用户</li>
<li>再次注册一个用户名为 <code>&lt;script&gt;alert(1)&lt;/script&gt;</code> 的用户</li>
<li>触发 duplicate key 异常，导致 XSS 漏洞</li>
</ol>
<p>访问 <code>http://your-ip:8000/create_user/?username=&lt;script&gt;alert(1)&lt;/script&gt;</code> 创建一个用户，成功；再次访问 <code>http://your-ip:8000/create_user/?username=&lt;script&gt;alert(1)&lt;/script&gt;</code>，触发异常：</p>
<p><img alt="image-20220222145930331" src="../images/202202221459394.png" /></p>
<p><img alt="image-20220222150104359" src="../images/202202221501499.png" /></p>
<p>可见，Postgres 抛出的异常为</p>
<div class="highlight"><pre><span></span><code>duplicate key value violates unique constraint &quot;xss_user_username_key&quot;
DETAIL:  Key (username)=(&lt;script&gt;alert(1)&lt;/script&gt;) already exists.
</code></pre></div>
<p>这个异常被拼接进 <code>The above exception ({{ frame.exc_cause }}) was the direct cause of the following exception</code>，最后触发 XSS。</p>

  <br>
    

    
    
      
    

  <div class="row wm-article-nav-buttons" role="navigation" aria-label="navigation">
    
    <div class="wm-article-nav pull-right">
      <a href="../FastAdmin%20%E8%BF%9C%E7%A8%8B%E4%BB%A3%E7%A0%81%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E/" class="btn btn-xs btn-default pull-right">
        Next
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
      </a>
      <a href="../FastAdmin%20%E8%BF%9C%E7%A8%8B%E4%BB%A3%E7%A0%81%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E/" class="btn btn-xs btn-link">
        FastAdmin 远程代码执行漏洞
      </a>
    </div>
    
    <div class="wm-article-nav">
      <a href="../Django%20Trunc%28kind%29%20and%20Extract%28lookup_name%29%20SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E%20CVE-2022-34265/" class="btn btn-xs btn-default pull-left">
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
        Previous</a><a href="../Django%20Trunc%28kind%29%20and%20Extract%28lookup_name%29%20SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E%20CVE-2022-34265/" class="btn btn-xs btn-link">
        Django Trunc(kind) and Extract(lookup_name) SQL 注入漏洞 CVE-2022-34265
      </a>
    </div>
    
  </div>

    <br>
</div>

<footer class="col-md-12 wm-page-content"><p>Copyright © 2025 SecNN-Wiki</p>
  <p>Documentation built with <a href="http://www.mkdocs.org/">MkDocs</a> using <a href="None">Windmill Dark</a> theme by 内部使用 (noraj).</p>
</footer>

</body>
</html>